// Import PropTypes.  
import PropTypes from 'prop-types';

// Display the array of objects, if the object's completed property is true, text color is grey, otherwise, text color is red.  
// There will gbe a strike through for the text if the object's completed property is true.  
// Each <li> element that is generated by the map method should have a different key, I set the key equals to each object's corresponding id.  
function ShoppingListItem({item, quantity, completed}) {
    return <li 
            style={{color: completed ? "grey" : "red", 
            textDecoration: completed ? "line-through" : "none"}}>
                {item} - {quantity}</li>;
}

// Define the PropTypes of each variable.  
ShoppingListItem.propTypes = {
    item: PropTypes.string, 
    quantity: PropTypes.number, 
    completed: PropTypes.bool
}

export default ShoppingListItem;